### ISSUE TITLE
SingleM Dev "Exception: condense requires input archive OTU tables"

### ISSUE THREAD

**Issue by julianzaugg** [wwood/singlem#102]
Hi Ben,

I was trying the latest dev version of SingleM and had the following error when trying to `condense` the metapackage OTU table.
```
09/14/2022 10:53:18 AM INFO: SingleM v0.13.2
09/14/2022 10:53:18 AM INFO: Loaded 59 SingleM packages
09/14/2022 10:53:18 AM INFO: Using as input 2 different pairs of sequence files e.g. /srv/projects/julian/MICR3004/shotgun/2_data/reads/RA2050_J4697_S64_R1_001.fastq.gz & /srv/projects/julian/MICR3004/shotgun/2_data/reads/RA2050_J4697_S64_R2_001.fastq.gz
09/14/2022 10:53:18 AM INFO: Filtering sequence files through DIAMOND blastx
09/14/2022 10:58:42 AM INFO: Finished DIAMOND prefilter phase
09/14/2022 10:58:42 AM INFO: Assigning sequences to SingleM packages with DIAMOND ..
09/14/2022 10:58:49 AM INFO: Running taxonomic assignment ..
09/14/2022 11:02:05 AM INFO: Finished running taxonomic assignment
09/14/2022 11:02:39 AM INFO: Finished
09/14/2022 11:02:40 AM INFO: SingleM v0.13.2
Traceback (most recent call last):
  File "/opt/centos7/sw/miniconda3/envs/singlem_dev_140922/bin/singlem", line 1099, in <module>
    otus = generate_streaming_otu_table_from_args(args, input_prefix=True, archive_only=True, min_archive_otu_table_version=4)
  File "/opt/centos7/sw/miniconda3/envs/singlem_dev_140922/bin/singlem", line 630, in generate_streaming_otu_table_from_args
    raise Exception("{} requires input archive OTU tables".format(args.subparser_name))
Exception: condense requires input archive OTU tables
```

Thoughts?

This previously worked on the dev version from ~31/05/22. Quite possibly I did not install the latest dev version correctly, it was a bit of a hack job to get running.

My run script is as follows:
```
conda activate singlem_dev_140922

READS_DIR="my/read/dir"
SINGLEM_DIR="my/singlem/dir"

mkdir -p $SINGLEM_DIR

THREADS=40
METAPACKAGE="/srv/db/singlem_packages/S3.metapackage_20220906.smpkg"

# Generate OTU table using forward and reverse reads for all samples
singlem pipe \
    --singlem-metapackage $METAPACKAGE \
    --forward $READS_DIR/RA205[0-1]*_R1_001.fastq.gz --reverse $READS_DIR/RA205[0-1]*_R2_001.fastq.gz \
    --otu_table $SINGLEM_DIR/metagenome.otu_table.tsv \
    --threads $THREADS \
    --assignment-threads $THREADS

# Combine OTU tables across multiple markers into a single OTU table.
# Only doing this for the read output to generate a community profile, but probably could do for assemblies/bins
singlem condense \
    --singlem-metapackage $METAPACKAGE \
    --input-otu-tables $SINGLEM_DIR/metagenome.otu_table.tsv \
    --output-otu-table $SINGLEM_DIR/metagenome_condensed.tsv \
    --krona $SINGLEM_DIR/metagenome_krona
```

**Comment by wwood** [comment]
Yeh just like it says - regular otu tables can no longer be used as input - output an archive-otu-table from pipe instead.

In future there'll just be a direct output of condensed profiles from pipe.

**Comment by julianzaugg** [comment]
Ah yes, that did the trick. I assumed that `condense` would work with regular OTU tables as the input option was still available (I guess this will be removed at some point).

Thanks.

**Comment by wwood** [comment]
Yep. It already is fixed actually in the breaking_changes branch.
