### ISSUE TITLE
condense ZeroDivisionError in calculating abundances

### ISSUE THREAD

**Issue by rzhao-2** [wwood/singlem#106]
Hi Ben,

Ran into this issue while testing condense for a viral metapackage. Noting the debug, condense seems to have removed the markers for this Bacteria taxonomy as an off-target hit (intentional? Input reads for pipe were all viral), but kept the coverages. Hence, the ZeroDivisionError when calculating abundance for genus expectation maximization.

```
09/16/2022 11:43:41 AM DEBUG: Using 0 markers for OTU taxonomy Root;d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__Klebsiella, with coverages dict_values([7.417582417582416, 2.4725274725274717, 10.400849150849147, 13.73626373626374, 11.744505494505491, 1.4835164835164834, 7.417582417582416, 10.027472527472526, 3.708791208791208])
Traceback (most recent call last):
  File "bin/singlem", line 1110, in <module>
    output_after_em_otu_table = args.output_after_em_otu_table)
  File "/mnt/home/n10927662/singlem-dev/bin/../singlem/condense.py", line 58, in condense
    CondensedCommunityProfileKronaWriter.write_krona(to_yield, krona_output_file)
  File "/mnt/home/n10927662/singlem-dev/bin/../singlem/condense.py", line 905, in write_krona
    for prof in condensed_profiles:
  File "/mnt/home/n10927662/singlem-dev/bin/../singlem/condense.py", line 108, in _condense_to_otu_table
    True, apply_diamond_expectation_maximisation, singlem_package_objects, output_after_em_otu_table)
  File "/mnt/home/n10927662/singlem-dev/bin/../singlem/condense.py", line 133, in _condense_a_sample
    sample_otus = self._apply_genus_expectation_maximization(sample_otus, target_domains)
  File "/mnt/home/n10927662/singlem-dev/bin/../singlem/condense.py", line 374, in _apply_genus_expectation_maximization
    core_return = self._apply_genus_expectation_maximization_core(sample_otus, 0, genes_per_domain)
  File "/mnt/home/n10927662/singlem-dev/bin/../singlem/condense.py", line 471, in _apply_genus_expectation_maximization_core
    trimmed_mean = self.calculate_abundance(list(gene_to_coverage.values()), num_markers, trim_percent)
  File "/mnt/home/n10927662/singlem-dev/bin/../singlem/condense.py", line 333, in calculate_abundance
    return sum(coverages) / total_num_measures
ZeroDivisionError: float division by zero
```

Thoughts?

**Comment by wwood** [comment]
Hmm, can give me the command you used? Possibly better to communicate via email - up to you.
