### ISSUE TITLE
Data version, maybe

### ISSUE THREAD

**Issue by ganiatgithub** [wwood/singlem#114]
Hi,

I installed v1.0.0beta2, ran into the following when checking  data installation, any tips?

```
(singlem-1.0.0beta2) singlem data --output-directory /fs03/rp24/Database/SingleM_package/gaofeng
10/21/2022 08:28:00 PM INFO: SingleM v1.0.0beta2
10/21/2022 08:28:00 PM INFO: Downloading data with ZenodoBackpack ..
10/21/2022 08:28:05 PM INFO: Downloading https://zenodo.org/api/files/557f0436-f6ad-448f-8ba5-e122222b1173/S3.0.5.metapackage20220806.smpkg.zb.tar.gz to /fs03/rp24/Database/SingleM_package/gaofeng/S3.0.5.metapackage20220806.smpkg.zb.tar.gz.
100%|████████████████████████████████████████████████████████████████████████████████████████████| 1.60G/1.60G [02:38<00:00, 10.1MiB/s]
10/21/2022 08:30:49 PM INFO: Extracting files from archive...
10/21/2022 08:32:39 PM INFO: Verifying version and checksums...
10/21/2022 08:32:53 PM INFO: Verification success.
10/21/2022 08:32:53 PM INFO: Finished downloading data
10/21/2022 08:32:53 PM INFO: The environment variable SINGLEM_METAPACKAGE_PATH can now be set to /fs03/rp24/Database/SingleM_package/gaofeng
10/21/2022 08:32:53 PM INFO: For instance, the following can be included in your .bashrc (requires logout and login after inclusion):
10/21/2022 08:32:53 PM INFO: export SINGLEM_METAPACKAGE_PATH='/fs03/rp24/Database/SingleM_package/gaofeng/S3.0.5.metapackage20220806.smpkg.zb/payload_directory'

(singlem-1.0.0beta2) singlem data --verify-only --debug
10/21/2022 08:34:21 PM INFO: SingleM v1.0.0beta2
10/21/2022 08:34:21 PM INFO: Acquiring SingleM packages from environment variable
10/21/2022 08:34:21 PM INFO: Retrieval successful. Location of backpack is: /fs03/rp24/Database/SingleM_package/gaofeng/S3.0.5.metapackage20220806.smpkg.zb/payload_directory
Traceback (most recent call last):
  File "/home/gnii0001/rp24/gaofeng/tools/singlem/bin/singlem", line 1084, in <module>
    Metapackage.verify(output_directory = args.output_directory)
  File "/fs04/rp24/gaofeng/tools/singlem/bin/../singlem/metapackage.py", line 133, in verify
    backpack = zenodo_backpack.acquire(env_var_name=DATA_ENVIRONMENT_VARIABLE, version=DATA_DEFAULT_VERSION)
  File "/home/gnii0001/rp24/gaofeng/tools/Miniconda3/envs/singlem-1.0.0beta2/lib/python3.9/site-packages/zenodo_backpack/__init__.py", line 121, in acquire
    if version != zb.data_version_string():
  File "/home/gnii0001/rp24/gaofeng/tools/Miniconda3/envs/singlem-1.0.0beta2/lib/python3.9/site-packages/zenodo_backpack/__init__.py", line 71, in data_version_string
    return self.contents[DATA_VERSION]
KeyError: 'data_version'
```

Thanks!!

**Comment by wwood** [comment]
Ah right, tis a bug - verify should be operating on the directory up, not payload directory. But not to fear, the data was verified after download, so you should be fine to go ahead without running --verify-only

will fix.

**Comment by ganiatgithub** [comment]
Thanks, still got the same when running with reads:

```
singlem pipe -1 $forward -2 $reverse --otu-table $SingleM_DIR/"$base"_otu_table.tsv --taxonomic-profile-krona $SingleM_DIR/"$base"_profile.html --threads 12 

10/21/2022 09:04:33 PM INFO: SingleM v1.0.0beta2
10/21/2022 09:04:33 PM INFO: Retrieval successful. Location of backpack is: /fs03/rp24/Database/SingleM_package/gaofeng/S3.0.5.metapackage20220806.smpkg.zb/payload_directory
Traceback (most recent call last):
  File "/home/gnii0001/rp24/gaofeng/tools/singlem/bin/singlem", line 559, in <module>
    singlem.pipe.SearchPipe().run(
  File "/fs04/rp24/gaofeng/tools/singlem/bin/../singlem/pipe.py", line 57, in run
    metapackage = self._parse_packages_or_metapackage(**kwargs)
  File "/fs04/rp24/gaofeng/tools/singlem/bin/../singlem/pipe.py", line 96, in _parse_packages_or_metapackage
    return Metapackage.acquire_default()
  File "/fs04/rp24/gaofeng/tools/singlem/bin/../singlem/metapackage.py", line 62, in acquire_default
    backpack = zenodo_backpack.acquire(env_var_name=DATA_ENVIRONMENT_VARIABLE, version=DATA_DEFAULT_VERSION)
  File "/home/gnii0001/rp24/gaofeng/tools/Miniconda3/envs/singlem-1.0.0beta2/lib/python3.9/site-packages/zenodo_backpack/__init__.py", line 121, in acquire
    if version != zb.data_version_string():
  File "/home/gnii0001/rp24/gaofeng/tools/Miniconda3/envs/singlem-1.0.0beta2/lib/python3.9/site-packages/zenodo_backpack/__init__.py", line 71, in data_version_string
    return self.contents[DATA_VERSION]
KeyError: 'data_version'
```

**Comment by wwood** [comment]
Oh, actually this is a bug in the way `data` suggests the env var

```
export SINGLEM_METAPACKAGE_PATH='/fs03/rp24/Database/SingleM_package/gaofeng/S3.0.5.metapackage20220806.smpkg.zb
```

**Comment by ganiatgithub** [comment]
Brilliant, should have spotted it, thank you!!

**Comment by wwood** [comment]
Not at all - my fault entirely. Thanks for the bug report. Should be fixed now.
