### ISSUE TITLE
Version in CONTENTS.json: 3.2.0 does not match version provided: 3.1

### ISSUE THREAD

**Issue by michoug** [wwood/singlem#130]
Hi
There is an issue with the newest version of the Zenodo metapackage apparently

```
05/23/2023 11:30:50 AM INFO: SingleM v1.0.0beta5
05/23/2023 11:30:50 AM INFO: Retrieval successful. Location of backpack is: /work/river/Software/singlem/data/S3.2.0.GTDB_r214.metapackage_20230428.smpkg.zb
Traceback (most recent call last):
  File "/work/river/Software/singlem/bin/singlem", line 606, in <module>
    singlem.pipe.SearchPipe().run(
  File "/work/river/Software/singlem/bin/../singlem/pipe.py", line 59, in run
    metapackage = self._parse_packages_or_metapackage(**kwargs)
  File "/work/river/Software/singlem/bin/../singlem/pipe.py", line 101, in _parse_packages_or_metapackage
    return Metapackage.acquire_default()
  File "/work/river/Software/singlem/bin/../singlem/metapackage.py", line 71, in acquire_default
    backpack = zenodo_backpack.acquire(env_var_name=DATA_ENVIRONMENT_VARIABLE, version=DATA_DEFAULT_VERSION)
  File "/work/river/Software/miniconda3/envs/singlem/lib/python3.10/site-packages/zenodo_backpack/__init__.py", line 122, in acquire
    raise ZenodoBackpackMalformedException(
zenodo_backpack.ZenodoBackpackMalformedException: Version in CONTENTS.json: 3.2.0 does not match version provided: 3.1.
```

Best
Greg

**Comment by wwood** [comment]
Ah sorry. Fixed on the supplement2 branch, which I'll merge tmr.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: michoug ***@***.***>
Sent: Tuesday, May 23, 2023 7:36:46 PM
To: wwood/singlem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/singlem] Version in CONTENTS.json: 3.2.0 does not match version provided: 3.1 (Issue #130)


Hi
There is an issue with the newest version of the Zenodo metapackage apparently

05/23/2023 11:30:50 AM INFO: SingleM v1.0.0beta5
05/23/2023 11:30:50 AM INFO: Retrieval successful. Location of backpack is: /work/river/Software/singlem/data/S3.2.0.GTDB_r214.metapackage_20230428.smpkg.zb
Traceback (most recent call last):
  File "/work/river/Software/singlem/bin/singlem", line 606, in <module>
    singlem.pipe.SearchPipe().run(
  File "/work/river/Software/singlem/bin/../singlem/pipe.py", line 59, in run
    metapackage = self._parse_packages_or_metapackage(**kwargs)
  File "/work/river/Software/singlem/bin/../singlem/pipe.py", line 101, in _parse_packages_or_metapackage
    return Metapackage.acquire_default()
  File "/work/river/Software/singlem/bin/../singlem/metapackage.py", line 71, in acquire_default
    backpack = zenodo_backpack.acquire(env_var_name=DATA_ENVIRONMENT_VARIABLE, version=DATA_DEFAULT_VERSION)
  File "/work/river/Software/miniconda3/envs/singlem/lib/python3.10/site-packages/zenodo_backpack/__init__.py", line 122, in acquire
    raise ZenodoBackpackMalformedException(
zenodo_backpack.ZenodoBackpackMalformedException: Version in CONTENTS.json: 3.2.0 does not match version provided: 3.1.


Best
Greg

―

**Comment by wwood** [comment]
You can also just manually specify the 3.2 package with --metapackage and it shouldn't complain.
