### ISSUE TITLE
Error running singlem

### ISSUE THREAD

**Issue by Ge0rges** [wwood/singlem#142]
Opening an issue encountered when running singlem originally posted [here](https://github.com/rhysnewell/aviary/issues/152). 

```
09/15/2023 03:19:36 AM INFO: Using as input 24 different sequence files e.g. bins/final_bins/concoct_bins.tsv.017_sub.fna
09/15/2023 03:19:36 AM INFO: Searching with 14 SingleM package(s)
09/15/2023 03:19:36 AM INFO: Searching for reads matching 28 different protein HMM(s)
09/15/2023 03:20:59 AM INFO: Finished search phase
09/15/2023 03:20:59 AM INFO: Running separate alignments in GraftM..
09/15/2023 03:22:31 AM INFO: Finished extracting aligned sequences
09/15/2023 03:22:31 AM INFO: Running taxonomic assignment with GraftM..
09/15/2023 03:34:44 AM INFO: Finished running taxonomic assignment with GraftM
09/15/2023 03:34:45 AM INFO: Finished
09/15/2023 03:34:50 AM INFO: Using as input 1 different sequence files e.g. /localdata/researchdrive/gkanaan/seaice_methylation/medaka/consensus.fasta
09/15/2023 03:34:50 AM INFO: Searching with 14 SingleM package(s)
09/15/2023 03:34:50 AM INFO: Searching for reads matching 28 different protein HMM(s)
09/15/2023 03:36:49 AM INFO: Finished search phase
09/15/2023 03:36:49 AM INFO: Running separate alignments in GraftM..
09/15/2023 03:37:41 AM INFO: Finished extracting aligned sequences
09/15/2023 03:37:41 AM INFO: Running taxonomic assignment with GraftM..
09/15/2023 03:51:06 AM INFO: Finished running taxonomic assignment with GraftM
09/15/2023 03:51:07 AM INFO: Finished
09/15/2023 03:51:12 AM INFO: Read in 186 markers from the different genomes
09/15/2023 03:51:12 AM INFO: After excluding duplicate markers that may indicate contamination, found 118 markers
09/15/2023 03:51:12 AM INFO: Read in 118 unique sequences from the 20 reference genomes
Traceback (most recent call last):
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/bin/singlem", line 744, in <module>
    output_svg=args.plot)
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/appraisal_result.py", line 71, in plot
    genes_to_plot = [self._pick_representative_marker(doing_assembly, doing_binning)]
  File "/Accounts/gkanaan/.conda/envs/76d4402d2c817b4f425630b066f34020_/lib/python3.6/site-packages/singlem/appraisal_result.py", line 167, in _pick_representative_marker
    key = lambda marker: sum(marker_to_distances[marker]))
ValueError: min() arg is an empty sequence
```

**Comment by wwood** [comment]
Hi,

Thank you for continuing to report bugs for Aviary and SingleM - much appreciated.

I believe the base issue here is that the singlem conda is several years out of date, and bitrot has set in. I hope to release a new version later this week, and then integrate that into Aviary - hopefully not too hard as I don't think the UI has changed too much, but famous last words...

Thanks,
ben

**Comment by Ge0rges** [comment]
Thank you for making great tools! I will leave you with the discretion of closing this issue. Please let me know if I can help in any way.

**Comment by wwood** [comment]
I believe this is now fixed in aviary and there is a new version of SingleM in bioconda.
