### ISSUE TITLE
Key error when running singlem data

### ISSUE THREAD

**Issue by Ge0rges** [wwood/singlem#146]
Hello, 

I'm having a key error when trying to run `singlem data`.

I execute `singlem data --output-directory /researchdrive/tools/singlem_data`

and obtain:
```
10/22/2023 02:33:47 AM INFO: SingleM v0.15.0
10/22/2023 02:33:47 AM INFO: Downloading data with ZenodoBackpack ..
Traceback (most recent call last):
  File "/Accounts/gkanaan/.conda/envs/read_qc/bin/singlem", line 1229, in <module>
    Metapackage.download(
  File "/Accounts/gkanaan/.conda/envs/read_qc/lib/python3.10/site-packages/singlem/metapackage.py", line 138, in download
    backpack = zenodo_backpack.ZenodoBackpackDownloader().download_and_extract(
  File "/Accounts/gkanaan/.conda/envs/read_qc/lib/python3.10/site-packages/zenodo_backpack/__init__.py", line 166, in download_and_extract
    fname = str(file['key']).split('/')[-1]
KeyError: 'key'
```

**Comment by wwood** [comment]
Hi,

Thanks for the report.

I'm away from the office for a few weeks, but as a workaround you can download the data from https://zenodo.org/records/8419620 and then unpack the tar.gz and set the SINGLEM_METAPACKAGE_PATH to the unpacked directory.

**Comment by wwood** [comment]
Hi,

I'm wondering whether this was a transient error that has now been fixed, possibly due to an issue with the zenodo API? The command now works for me.

**Comment by Ge0rges** [comment]
Indeed seems like it works now!
