### ISSUE TITLE
OSError: [Errno 24] Too many open files during in running singlem pipe

### ISSUE THREAD

**Issue by WoCer2019** [wwood/singlem#150]
Thanks for the nice tool!

I use this tool to determine how much of a community is represented by a set of genomes (dereplicated MAGs). Now, I have about 1800 dereplicated MAGs. According to the pipeline, I first run:`singlem pipe --sequences raw.fq.gz --otu-table metagenome.otu_table.csv`. It's ok! But I run: `singlem pipe --genome-fasta-files derep_MAG/output/*.fa --otu-table metagenome_otu_table.tsv`. There is an error：
```
11/20/2023 03:35:51 PM INFO: SingleM v0.15.1
11/20/2023 03:35:51 PM INFO: Retrieval successful. Location of backpack is: /media/database/singlem/S3.2.1.GTDB_r214.metapackage_20231006.smpkg.zb
11/20/2023 03:35:51 PM INFO: Loaded 59 SingleM packages
11/20/2023 03:35:51 PM WARNING: Running singlem with more than 100 genomes may take a long time or use a lot of RAM - you might be better off splitting them into batches. Consider also using --no-assign-taxonomy to speed things up.
11/20/2023 03:35:51 PM INFO: Calling rough transcriptome of genome FASTA files
Traceback (most recent call last):
  File "/home/miniconda3/envs/singlem/bin/singlem", line 650, in <module>
    singlem.pipe.SearchPipe().run(
  File "/home/miniconda3/envs/singlem/lib/python3.10/site-packages/singlem/pipe.py", line 68, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/home/miniconda3/envs/singlem/lib/python3.10/site-packages/singlem/pipe.py", line 270, in run_to_otu_table
    extern.run('orfm -c {} -m {} -t {} {} >/dev/null'.format(self._translation_table, self._min_orf_length, transcripts_path.name, fasta))
  File "/home/miniconda3/envs/singlem/lib/python3.10/site-packages/extern/__init__.py", line 34, in run
    process = subprocess.run(
  File "/home/miniconda3/envs/singlem/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/miniconda3/envs/singlem/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/miniconda3/envs/singlem/lib/python3.10/subprocess.py", line 1762, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
```
If I get a result from this step, I can continue after step (singlem appraise). 

Do you have any good solutions or suggestions?

Thanks in advance！

WarrenYates

**Comment by wwood** [comment]
Hi,

Thanks.

Currently SingleM isn't designed to take so many individual input files. I suggest running them in batches and then combining them using SingleM summarise or just using cat if you want to be low tech.

The parallel and split tools may help on the command line.

Arguably this is an issue, but not the highest priority so don't wait on a fix.

**Comment by WoCer2019** [comment]
Hi,

Thanks for your reply!
