### ISSUE TITLE
singlem data --output-directory OUTPUT_DIRECTORY encountered several issues

### ISSUE THREAD

**Issue by LvbBo** [wwood/singlem#154]
Hi:
         there are several issues need your help!

1. after installed singlem, i want to procure the reference data (the "metapackage"). so i used singlem data --output-directory to download that data, but i encountered the following problems and i can't solve it, please help me !

here are the issues:
(singlem) [Lvgongbo@localhost OUTPUT_DIRECTORY]$ singlem data --output-directory OUTPUT_DIRECTORY
01/15/2024 10:50:10 AM INFO: SingleM v0.16.0
01/15/2024 10:50:10 AM INFO: Downloading data with ZenodoBackpack ..
Traceback (most recent call last):
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9d54130520>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/5739611 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d54130520>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/zenodo_backpack/__init__.py", line 302, in _retrieve_record_ID
    r = requests.get(doi, timeout=15.)
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/5739611 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d54130520>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data3/lgb_data_softwear/nosZ_Reference_amino_acid/singlem/bin/singlem", line 1253, in <module>
    Metapackage.download(
  File "/data3/lgb_data_softwear/nosZ_Reference_amino_acid/singlem/bin/../singlem/metapackage.py", line 138, in download
    backpack = zenodo_backpack.ZenodoBackpackDownloader().download_and_extract(
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/zenodo_backpack/__init__.py", line 160, in download_and_extract
    recordID = self._retrieve_record_ID(doi)
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/zenodo_backpack/__init__.py", line 304, in _retrieve_record_ID
    raise ZenodoConnectionException('Connection error: {}'.format(e))
zenodo_backpack.ZenodoConnectionException: Connection error: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/5739611 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d54130520>: Failed to establish a new connection: [Errno 111] Connection refused'))

I am not sure what went wrong. Could you please help me fix it?
best wishes
 LvbBO

**Comment by wwood** [comment]
Hi,

This seems either to be a transient thing with zenodo or some firewall issue on your server. You can download it manually from https://zenodo.org/records/8419620

**Comment by LvbBo** [comment]
Hi: 
thanks for your reply, the issue was solved, but a new issue : 
(singlem) [Lvgongbo@localhost bin]$  singlem pipe -1 /data3/lgb_data_softwear/JM_N_clean_data/JM5.clean.1.fastq -2 /data 3/lgb_data_softwear/JM_N_clean_data/JM5.clean.2.fastq --otu-table /data3/lgb_data_softwear/JM5_outputotu_table.tsv
01/15/2024 04:19:49 PM INFO: SingleM v0.16.0
01/15/2024 04:19:49 PM INFO: Retrieval successful. Location of backpack is: /data3/lgb_data_softwear/nosZ_Reference_amino_acid/singlem/bin/OUTPUT_DIRECTORY/S3.2.1.GTDB_r214.metapackage_20231006.smpkg.zb/payload_directory/
Traceback (most recent call last):
  File "/data3/lgb_data_softwear/nosZ_Reference_amino_acid/singlem/bin/singlem", line 662, in <module>
    singlem.pipe.SearchPipe().run(
  File "/data3/lgb_data_softwear/nosZ_Reference_amino_acid/singlem/bin/../singlem/pipe.py", line 62, in run
    metapackage = self._parse_packages_or_metapackage(**kwargs)
  File "/data3/lgb_data_softwear/nosZ_Reference_amino_acid/singlem/bin/../singlem/pipe.py", line 104, in _parse_packages_or_metapackage
    return Metapackage.acquire_default()
  File "/data3/lgb_data_softwear/nosZ_Reference_amino_acid/singlem/bin/../singlem/metapackage.py", line 71, in acquire_default
    backpack = zenodo_backpack.acquire(env_var_name=DATA_ENVIRONMENT_VARIABLE, version=DATA_DEFAULT_VERSION)
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/zenodo_backpack/__init__.py", line 121, in acquire
    if version != zb.data_version_string():
  File "/data3/lgb_data_softwear/miniconda/envs/singlem/lib/python3.10/site-packages/zenodo_backpack/__init__.py", line 71, in data_version_string
    return self.contents[DATA_VERSION]
KeyError: 'data_version'
should i update this data_version or what should i do sth and how can i do it ？
please give me some suggestions, thanks very much !!!

**Comment by wwood** [comment]
Reckon you might have specified the env var wrongly. Did you put payload directory in it? It shouldn't be.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
