### ISSUE TITLE
zenodo_backpack.ZenodoBackpackMalformedException

### ISSUE THREAD

**Issue by dawnmy** [wwood/singlem#175]
Hi, I am testing SingleM v0.16.0 with the default reference data downloaded by: `singlem data --output-directory`, but got the following error message:

```
04/29/2024 02:08:40 PM INFO: SingleM v0.16.0
04/29/2024 02:08:40 PM INFO: Retrieval successful. Location of backpack is: /dbs/singlem/S3.1.2.GTDB_r207.metapackage_20240405.smpkg.zb
Traceback (most recent call last):
  File "/home/user/miniconda3/bin/singlem", line 658, in <module>
    singlem.pipe.SearchPipe().run(
  File "/home/user/miniconda3/lib/python3.9/site-packages/singlem/pipe.py", line 63, in run
    metapackage = self._parse_packages_or_metapackage(**kwargs)
  File "/home/user/miniconda3/lib/python3.9/site-packages/singlem/pipe.py", line 105, in _parse_packages_or_metapackage
    return Metapackage.acquire_default()
  File "/home/user/miniconda3/lib/python3.9/site-packages/singlem/metapackage.py", line 71, in acquire_default
    backpack = zenodo_backpack.acquire(env_var_name=DATA_ENVIRONMENT_VARIABLE, version=DATA_DEFAULT_VERSION)
  File "/home/user/miniconda3/lib/python3.9/site-packages/zenodo_backpack/__init__.py", line 122, in acquire
    raise ZenodoBackpackMalformedException(
zenodo_backpack.ZenodoBackpackMalformedException: Version in CONTENTS.json: 3.1.2 does not match version provided: 3.2.1
```

How can I solve it? Is this because the downloaded metapackage set a wrong version?

**Comment by wwood** [comment]
Ah right. No, I messed up. 

You can download the 3.2.1 version manually from https://zenodo.org/records/8419620

New release coming soon which will fix this.

**Comment by dawnmy** [comment]
Thanks. It works
