### ISSUE TITLE
Singlem 0.16.0

### ISSUE THREAD

**Issue by A1exanderW** [wwood/singlem#197]
Hi, I'm trying to run singlem/0.16.0 from the modules available on UQ bunya compute nodes. 
After I download, install the metapackage: s4 .3.0.GTDB_r220.metapackage_20240523.smpkg.zb. 
and I set the SINGLEM_METAPACKAGE_PATH to the relevant scratch folder. But when I tried run the pipe command I received an error about: Environment variable SINGLEM_METAPACKAGE_PATH does not contain a CONTENTS.json file, so is not a valid ZenodoBackpack. 

So I tried to download the package from the Zenodo site, extracted the file on my local computer (tar -xzf in cmd prompt) and copied the directory over to the HPC. This seemed to make a difference as the error (copied below) I received was now about the json file not matching up. 

Am I right to think that the metapackage version is incompatible with v 0.16.0 of singleM? 
Could you please let me know which metapackage I should be installing?
Thanks

10/18/2024 03:01:20 PM INFO: Retrieval successful. Location of backpack is: /scratch/user/u                                            qawang8/tmp/S4.3.0.GTDB_r220.metapackage_20240523.smpkg.zb
Traceback (most recent call last):
  File "/sw/local/rocky8/noarch/qcif/software/miniconda3/envs/singlem_0.16.0/bin/singlem", line 658, in <module>
    singlem.pipe.SearchPipe().run(
  File "/sw/local/rocky8/noarch/qcif/software/miniconda3/envs/singlem_0.16.0/lib/python3.10/site-packages/singlem/pipe.py", line 63, in run
    metapackage = self._parse_packages_or_metapackage(**kwargs)
  File "/sw/local/rocky8/noarch/qcif/software/miniconda3/envs/singlem_0.16.0/lib/python3.10/site-packages/singlem/pipe.py", line 105, in _parse_packages_or_metapackage
    return Metapackage.acquire_default()
  File "/sw/local/rocky8/noarch/qcif/software/miniconda3/envs/singlem_0.16.0/lib/python3.10/site-packages/singlem/metapackage.py", line 71, in acquire_default
    backpack = zenodo_backpack.acquire(env_var_name=DATA_ENVIRONMENT_VARIABLE, version=DATA                              _DEFAULT_VERSION)
  File "/sw/local/rocky8/noarch/qcif/software/miniconda3/envs/singlem_0.16.0/lib/python3.10 /site-packages/zenodo_backpack/__init__.py", line 122, in acquire
    raise ZenodoBackpackMalformedException(
zenodo_backpack.ZenodoBackpackMalformedException: Version in CONTENTS.json: 4.3.0 does notmatch version provided: 3.2.1

**Comment by wwood** [comment]
Hi,

0.16.0 is out of date, I suggest updating. But if you must use 0.16, download an old version 3.2.1 from zenodo and then specify the metapackage with --metapackage when running pipe. That supercedes the environment variable.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: Alexander W ***@***.***>
Sent: Friday, October 18, 2024 3:13:39 PM
To: wwood/singlem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/singlem] Singlem 0.16.0 (Issue #197)


Hi, I'm trying to run singlem/0.16.0 from the modules available on UQ bunya compute nodes.
After I download, install the metapackage: s4 .3.0.GTDB_r220.metapackage_20240523.smpkg.zb.
and I set the SINGLEM_METAPACKAGE_PATH to the relevant scratch folder. But when I tried run the pipe command I received an error about: Environment variable SINGLEM_METAPACKAGE_PATH does not contain a CONTENTS.json file, so is not a valid ZenodoBackpack.

So I tried to download the package from the Zenodo site, extracted the file on my local computer (tar -xzf in cmd prompt) and copied the directory over to the HPC. This seemed to make a difference as the error (copied below) I received was now about the json file not matching up.

Am I right to think that the metapackage version is incompatible with v 0.16.0 of singleM?
Could you please let me know which metapackage I should be installing?
Thanks

10/18/2024 03:01:20 PM INFO: Retrieval successful. Location of backpack is: /scratch/user/u qawang8/tmp/S4.3.0.GTDB_r220.metapackage_20240523.smpkg.zb
Traceback (most recent call last):
File "/sw/local/rocky8/noarch/qcif/software/miniconda3/envs/singlem_0.16.0/bin/singlem", line 658, in
singlem.pipe.SearchPipe().run(
File "/sw/local/rocky8/noarch/qcif/software/miniconda3/envs/singlem_0.16.0/lib/python3.10/site-packages/singlem/pipe.py", line 63, in run
metapackage = self._parse_packages_or_metapackage(**kwargs)
File "/sw/local/rocky8/noarch/qcif/software/miniconda3/envs/singlem_0.16.0/lib/python3.10/site-packages/singlem/pipe.py", line 105, in _parse_packages_or_metapackage
return Metapackage.acquire_default()
File "/sw/local/rocky8/noarch/qcif/software/miniconda3/envs/singlem_0.16.0/lib/python3.10/site-packages/singlem/metapackage.py", line 71, in acquire_default
backpack = zenodo_backpack.acquire(env_var_name=DATA_ENVIRONMENT_VARIABLE, version=DATA _DEFAULT_VERSION)
File "/sw/local/rocky8/noarch/qcif/software/miniconda3/envs/singlem_0.16.0/lib/python3.10 /site-packages/zenodo_backpack/init.py", line 122, in acquire
raise ZenodoBackpackMalformedException(
zenodo_backpack.ZenodoBackpackMalformedException: Version in CONTENTS.json: 4.3.0 does notmatch version provided: 3.2.1

―

**Comment by A1exanderW** [comment]
Thank you!
