### ISSUE TITLE
Duplicate names amongst placed sequences

### ISSUE THREAD

**Issue by michoug** [wwood/singlem#32]
Hi,
When running the following command on ~240 genomes,

`singlem pipe --threads 10 --sequences dereplicated_genomes/*fa --otu_table genomes_otu_table.csv  `

 I get this error at the end

`Traceback (most recent call last):
  File "/home/michoug/miniconda2/bin/singlem", line 509, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/home/michoug/miniconda2/lib/python2.7/site-packages/singlem/pipe.py", line 46, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/home/michoug/miniconda2/lib/python2.7/site-packages/singlem/pipe.py", line 224, in run_to_otu_table
    package_to_taxonomy_bihash)
  File "/home/michoug/miniconda2/lib/python2.7/site-packages/singlem/pipe.py", line 602, in _process_taxonomically_assigned_reads
    new_infos = process_readset(maybe_paired_readset, analysing_pairs)
  File "/home/michoug/miniconda2/lib/python2.7/site-packages/singlem/pipe.py", line 549, in process_readset
    taxonomy_bihash)
  File "/home/michoug/miniconda2/lib/python2.7/site-packages/singlem/pipe.py", line 427, in extract_placement_parser
    jplace_json, taxonomy_bihash, placement_threshold)
  File "/home/michoug/miniconda2/lib/python2.7/site-packages/singlem/placement_parser.py", line 19, in __init__
    "There appears to be duplicate names amongst placed sequences")
Exception: There appears to be duplicate names amongst placed sequences
`

Any ideas ?

**Comment by wwood** [comment]
Hi there,
Apologies. I know of this error in the most recent version of singlem. I hope to have a fix available soon.
ben

**Comment by wwood** [comment]
Hi again,
I believe this issue has been fixed - it was actually in GraftM, a dependency of SingleM. If you upgrade GraftM to 0.12.1 this issue will hopefully go away. Let me know if not.
Thanks again for the bug report.
ben

**Comment by wwood** [comment]
Actually, sorry it seems I only fixed one reason this error was being thrown, so you most likely will still get the same error. Working on it now - thanks for your patience.

**Comment by wwood** [comment]
Hi, I reckon this is fixed now in the just released 0.12.1 - let me know if not.

**Comment by morgvevans** [comment]
Hi,
This tool is really great! Thanks for this.
I am however having an issue using singlem.
I am using the docker pull single m v.0.12.0 and getting this same error (only on bins but not on raw reads)

Is there a release for v.0.12.1 that I am not seeing in docker?

Thanks!

**Comment by morgvevans** [comment]
I have attached my script

10/23/2019 06:47:16 PM INFO: Using as input 7 different sequence files e.g. /fs/project/PAS1331/Latin_America/ES_P_Project/REASSEMBLED_BINS/SRR2938335/bin.1.permissive.fna
10/23/2019 06:47:16 PM INFO: Searching with 14 SingleM package(s)
10/23/2019 06:47:16 PM INFO: Searching for reads matching 28 different protein HMM(s)
10/23/2019 06:47:20 PM INFO: Finished search phase
10/23/2019 06:47:20 PM INFO: Running separate alignments in GraftM..
10/23/2019 06:47:26 PM INFO: Finished extracting aligned sequences
10/23/2019 06:47:26 PM INFO: Running taxonomic assignment with GraftM..
10/23/2019 06:53:00 PM INFO: Finished running taxonomic assignment with GraftM
Traceback (most recent call last):
  File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/bin/..singlem-real-real", line 509, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/pipe.py", line 46, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/pipe.py", line 224, in run_to_otu_table
    package_to_taxonomy_bihash)
  File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/pipe.py", line 602, in _process_taxonomically_assigned_reads
    new_infos = process_readset(maybe_paired_readset, analysing_pairs)
  File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/pipe.py", line 549, in process_readset
    taxonomy_bihash)
  File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/pipe.py", line 427, in extract_placement_parser
    jplace_json, taxonomy_bihash, placement_threshold)
  File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/placement_parser.py", line 19, in __init__
    "There appears to be duplicate names amongst placed sequences")
Exception: There appears to be duplicate names amongst placed sequences
[33mWARNING:[0m passwd file doesn't exist in container, not updating
[33mWARNING:[0m group file doesn't exist in container, not updating
Traceback (most recent call last):
  File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/bin/..singlem-real-real", line 701, in <module>
    with open(table) as f:
IOError: [Errno 2] No such file or directory: '../SingleM_OTU_vs_Bins/genomes.otu_table.csv'
