### ISSUE TITLE
Sequence file - is empty or misformatted

### ISSUE THREAD

**Issue by rachaellappan** [wwood/singlem#34]
Hi Ben,

When running SingleM I sometimes receive the following error (full output below). Does this simply mean that none of the reads aligned to any of the ribosomal proteins (and so a subsequent intermediate file is empty)?

I am analysing heavily human contaminated metagenomes, so this would make sense as I generally only have 200,000 to 300,000 read pairs per sample remaining - some samples don't receive this error and I get a (tiny) OTU table. 

However, for at least one sample the error occurs when I run paired reads with `--forward` and `--reverse`, but it successfully completes when I run the forward reads only (with very few reads in the resulting table, of course). Is this because the forward and reverse reads must both hit the marker? Isn't this detrimental to cases where, for example, the forward read lands towards the end of the marker sequence and the reverse read is outside? Likely not much of an issue when you have a far greater number of usable reads, but interested to hear your thoughts. 

Cheers,
Rachael
```
06/28/2019 01:22:12 PM INFO: Using as input 1 different sequence files e.g. /home/rlappan/scratch/sigmoid_human_clean_bbmap/SC6147_S5_human_clean_bbmap_1.fastq.gz
06/28/2019 01:22:12 PM INFO: Searching with 14 SingleM package(s)
06/28/2019 01:22:12 PM INFO: Searching for reads matching 28 different protein HMM(s)
06/28/2019 01:22:19 PM INFO: Finished search phase
06/28/2019 01:22:19 PM INFO: Running separate alignments in GraftM..
06/28/2019 01:22:22 PM INFO: Finished extracting aligned sequences
06/28/2019 01:22:22 PM INFO: Running taxonomic assignment with GraftM..
Traceback (most recent call last):
  File "/home/rlappan/miniconda2/envs/bioinfo/bin/singlem", line 509, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/singlem/pipe.py", line 46, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/singlem/pipe.py", line 205, in run_to_otu_table
    extracted_reads, graftm_assignment_method)
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/singlem/pipe.py", line 1021, in _assign_taxonomy
    extern.run_many(commands, num_threads=1)
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/extern/__init__.py", line 81, in run_many
    stdin=stdin)
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/extern/multi_runner.py", line 95, in run
    raise extern.ExternCalledProcessError(*res[2:])
extern.ExternCalledProcessError: Command graftM graft --verbosity 2 --input_sequence_type nucleotide  --min_orf_length 96   --filter_minimum 28  --threads 12 --graftm_package /home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ --max_samples_for_krona 0 --assignment_method pplacer --output_directory /dev/shm/tmpFLy7ID/graftm_aligns/S1.11.ribosomal_protein_S10_rpsJ  --forward /dev/shm/tmpFLy7ID/tmp/singlem.SC6147_S5_human_clean_bbmap_1hgr3l6.fasta --reverse /dev/shm/tmpFLy7ID/tmp/singlem.SC6147_S5_human_clean_bbmap_1RjkrmU.fasta returned non-zero exit status 1.
STDERR was: Traceback (most recent call last):
  File "/home/rlappan/miniconda2/envs/bioinfo/bin/graftM", line 411, in <module>
    Run(args).main()
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/graftm/run.py", line 592, in main
    self.graft()
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/graftm/run.py", line 377, in graft
    diamond_db
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/graftm/timeit.py", line 10, in timed
    result = method(*args, **kw)
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/graftm/sequence_searcher.py", line 821, in aa_db_search
    hit_reads_orfs_fasta)
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/graftm/sequence_searcher.py", line 883, in search_and_extract_orfs_matching_protein_database
    orfm
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/graftm/sequence_searcher.py", line 220, in hmmsearch
    searcher.hmmsearch(input_cmd, self.search_hmm, output_table_list)
  File "/home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/graftm/hmmsearcher.py", line 69, in hmmsearch
    raise e
extern.ExternCalledProcessError: Command orfm  -m 96 /dev/shm/tmpFLy7ID/tmp/singlem.SC6147_S5_human_clean_bbmap_1RjkrmU.fasta | tee >(hmmsearch --domE 1e-05 --cpu 6 -o /dev/null --noali --domtblout /dev/shm/tmpFLy7ID/graftm_aligns/S1.11.ribosomal_protein_S10_rpsJ/singlem.SC6147_S5_human_clean_bbmap_1hgr3l6/reverse/graftme9CA2v_search_singlem.SC6147_S5_human_clean_bbmap_1hgr3l6_reverse.hmmout.txt /home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftme9CA2v_search.hmm -) | hmmsearch --domE 1e-05 --cpu 6 -o /dev/null --noali --domtblout /dev/shm/tmpFLy7ID/graftm_aligns/S1.11.ribosomal_protein_S10_rpsJ/singlem.SC6147_S5_human_clean_bbmap_1hgr3l6/reverse/graftmmSefD1_search_singlem.SC6147_S5_human_clean_bbmap_1hgr3l6_reverse.hmmout.txt /home/rlappan/miniconda2/envs/bioinfo/lib/python2.7/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftmmSefD1_search.hmm - returned non-zero exit status 1.
STDERR was:
Error: Sequence file - is empty or misformatted


Error: Sequence file - is empty or misformatted

STDOUT was:
STDOUT was:
```

**Comment by wwood** [comment]
Hi,

Hmm, maybe, it is a little hard to tell. SingleM isn't supposed to croak so gracelessly when that happens, and it appears to have at least found some reads for some genes because it doesn't stop earlier.

Would you mind rerunning singlem using `--working_directory`, and then sending me that directory when it fails again please? Thanks. Not sure how big it is but maybe over email or via dropbox or similar..

Thanks, ben
