### ISSUE TITLE
singlem version issue: duplicate names amongst placed sequences...

### ISSUE THREAD

**Issue by morgvevans** [wwood/singlem#42]
This issue (https://github.com/wwood/singlem/issues/32) established that this error comes from an out of date graftm install 
I am using the most recent docker pull (v.0.12.0) but you mentioned this issue was fixed in v.0.12.1, is there a way to get this new docker image? or am I missing something?

Below is my output with the error
I have attached my script

10/23/2019 06:47:16 PM INFO: Using as input 7 different sequence files e.g. /fs/project/PAS1331/Latin_America/ES_P_Project/REASSEMBLED_BINS/SRR2938335/bin.1.permissive.fna
10/23/2019 06:47:16 PM INFO: Searching with 14 SingleM package(s)
10/23/2019 06:47:16 PM INFO: Searching for reads matching 28 different protein HMM(s)
10/23/2019 06:47:20 PM INFO: Finished search phase
10/23/2019 06:47:20 PM INFO: Running separate alignments in GraftM..
10/23/2019 06:47:26 PM INFO: Finished extracting aligned sequences
10/23/2019 06:47:26 PM INFO: Running taxonomic assignment with GraftM..
10/23/2019 06:53:00 PM INFO: Finished running taxonomic assignment with GraftM
Traceback (most recent call last):
File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/bin/..singlem-real-real", line 509, in
known_sequence_taxonomy = args.known_sequence_taxonomy)
File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/pipe.py", line 46, in run
otu_table_object = self.run_to_otu_table(**kwargs)
File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/pipe.py", line 224, in run_to_otu_table
package_to_taxonomy_bihash)
File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/pipe.py", line 602, in _process_taxonomically_assigned_reads
new_infos = process_readset(maybe_paired_readset, analysing_pairs)
File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/pipe.py", line 549, in process_readset
taxonomy_bihash)
File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/pipe.py", line 427, in extract_placement_parser
jplace_json, taxonomy_bihash, placement_threshold)
File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/lib/python2.7/site-packages/singlem/placement_parser.py", line 19, in init
"There appears to be duplicate names amongst placed sequences")
Exception: There appears to be duplicate names amongst placed sequences
�[33mWARNING:�[0m passwd file doesn't exist in container, not updating
�[33mWARNING:�[0m group file doesn't exist in container, not updating
Traceback (most recent call last):
File "/gnu/store/9h8r1vjzn3gbps87pchbhc2132p95fv6-singlem-0.12.0/bin/..singlem-real-real", line 701, in
with open(table) as f:
IOError: [Errno 2] No such file or directory: '../SingleM_OTU_vs_Bins/genomes.otu_table.csv'

**Comment by wwood** [comment]
Hi yes you are quite right. Other than installing SingleM outside docker in some way, I don't think there is currently a way around this.

I anticipate releasing a new version of both graftm and singlem next week (both upgraded to python3), and I'll make sure not to forgot to release the docker images this time.

Thanks for your support.

**Comment by morgvevans** [comment]
OK great, thanks so much for the update!

**Comment by wwood** [comment]
Hi, well I was a little later than "next week" but there's a docker image of 0.13.0 now, which should solve this problem.
