### ISSUE TITLE
singlem pipe ExternCalledProcessError

### ISSUE THREAD

**Issue by taylorreiter** [wwood/singlem#52]
Using command:
```
(singlem) $ singlem pipe --sequences ../../outputs/sgc_genome_queries/4000_k31_r1_search_oh0/ZeeviD_2015__PNP_Main_232__bin.27.fa.gz.cdbg_ids.reads.fa.gz --otu_t
able otu_table.csv --threads 2
```

I receive the following error:
```
07/27/2020 02:41:20 PM INFO: Using as input 1 different sequence files e.g. ../../outputs/sgc_genome_queries/4000_k31_r1_search_oh0/ZeeviD_2015__PNP_Main_232__bin.27.fa.gz.cdbg_ids.reads.fa.gz
07/27/2020 02:41:20 PM INFO: Searching with 14 SingleM package(s)
07/27/2020 02:41:20 PM INFO: Searching for reads matching 28 different protein HMM(s)
Traceback (most recent call last):
  File "/home/tereiter/miniconda3/envs/singlem/bin/singlem", line 513, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 45, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 176, in run_to_otu_table
    search_result = self._search(hmms, forward_read_files, reverse_read_files)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 860, in _search
    run(hmms, graftm_protein_search_directory, True)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 848, in run
    extern.run(cmd)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/extern/__init__.py", line 41, in run
    raise ExternCalledProcessError(process, command)
extern.ExternCalledProcessError: Command graftM graft --verbosity 2 --input_sequence_type nucleotide  --min_orf_length 96   --filter_minimum 28 --threads 2 --forward ../../outputs/sgc_genome_queries/4000_k31_r1_s
earch_oh0/ZeeviD_2015__PNP_Main_232__bin.27.fa.gz.cdbg_ids.reads.fa.gz --search_only --search_hmm_files /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gp
kg.spkg/S1.9.ribosomal_protein_S5/graftm4ehmqY_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftmBf7aFs
_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftm5WU6Uq_search.hmm /home/tereiter/minic
onda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftmSHqOh3_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6
/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmUShLiV_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.1.rib
osomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmY0W8yc_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S
1.11.ribosomal_protein_S10_rpsJ/graftme9CA2v_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/
graftmmSefD1_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmhZA_92_search.hmm /home/tereit
er/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmrgaTTv_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/pytho
n3.6/site-packages/singlem/data/S1.2.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmeZ00Qg_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.2
.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmID8t_I_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spk
g/S1.12.ribosomal_protein_S12_S23/graftmD68DOf_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spkg/S1.12.ribosomal_protein_S12_S23/
graftm4bucq1_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftmCpbnSc_search.hmm /home/tere
iter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftm5YNr6y_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/p
ython3.6/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmSIv4ri_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem
/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmh8KCUY_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.4.ribosomal_protein_L
6_rplF.gpkg.spkg/S1.4.ribosomal_protein_L6_rplF/graftmDE7_8b_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.4.ribosomal_protein_L6_rplF.gpkg.spkg/S1.4.ribosomal_prot
ein_L6_rplF/graftmr_l5Gy_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmAbXN7F
_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmWRo94z_search.hmm /home/tereit
er/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmFIm7K0_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/pytho
n3.6/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmMH5eE7_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.1
0.ribosomal_protein_S7.gpkg.spkg/S1.10.ribosomal_protein_S7/graftmunofJO_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.10.ribosomal_protein_S7.gpkg.spkg/S1.10.ribos
omal_protein_S7/graftmvR14Hx_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftm
AiWqW8_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftmIkMbHN_search.hmm --ou
tput_directory /dev/shm/tmp25jcs9e8/graftm_protein_search --aln_hmm_file /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_
S5/graftm4ehmqY_search.hmm  returned non-zero exit status 1.
STDERR was: b'Traceback (most recent call last):\n  File "/home/tereiter/miniconda3/envs/singlem/bin/graftM", line 415, in <module>\n    Run(args).main()\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python
3.6/site-packages/graftm/run.py", line 613, in main\n    self.graft()\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/run.py", line 388, in graft\n    diamond_db\n  File "/home/
tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/timeit.py", line 10, in timed\n    result = method(*args, **kw)\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graf
tm/sequence_searcher.py", line 851, in aa_db_search\n    hit_reads_orfs_fasta)\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 943, in search_and_ext
ract_orfs_matching_protein_database\n    hits\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 534, in _extract_from_raw_reads\n    extern.run(extract
_cmd, stdin=\'\\n\'.join(input_reads))\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/extern/__init__.py", line 41, in run\n    raise ExternCalledProcessError(process, command)\nexter
n.ExternCalledProcessError: Command mfqe --output-uncompressed --fasta-read-name-lists /dev/stdin --input-fasta <(zcat \'../../outputs/sgc_genome_queries/4000_k31_r1_search_oh0/ZeeviD_2015__PNP_Main_232__bin.27.f
a.gz.cdbg_ids.reads.fa.gz\') --output-fasta-files \'/tmp/_raw_extracted_reads.fa0upmhcxy\' returned non-zero exit status 101.\nSTDERR was: b"[2020-07-27T21:41:36Z INFO  mfqe] Read in 711 read names from /dev/stdi
n\\n[2020-07-27T21:41:36Z INFO  mfqe] Iterating input FASTQ file\\nthread \'main\' panicked at \'called `Result::unwrap()` on an `Err` value: InvalidStart { line: 1, found: 64 }\', src/libcore/result.rs:1084:5\\n
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n"STDOUT was: b\'\'\n'STDOUT was: b''
```

I used conda to install `singlem`, and my env looks like this:

```
$ conda list
# packages in environment at /home/tereiter/miniconda3/envs/singlem:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
backpack                  0.1                   py36_1000    conda-forge
biom-format               2.1.8            py36hc1659b7_0    conda-forge
biopython                 1.77             py36h8c4c3a4_0    conda-forge
blinker                   1.4                        py_1    conda-forge
boost-cpp                 1.70.0               h7b93d67_3    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py36h9f0ad1d_0    conda-forge
cleo                      0.6.8                      py_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
curl                      7.71.1               he644dc0_3    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
dendropy                  4.4.0              pyh864c0ab_2    bioconda
diamond                   2.0.0                h56fc30b_0    bioconda
expressbetadiversity      1.0.10               hc9558a2_0    bioconda
extern                    0.4.1                      py_0    conda-forge
faker                     0.8.13                     py_0    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
future                    0.18.2           py36h9f0ad1d_1    conda-forge
graftm                    0.13.1                     py_0    bioconda
h5py                      2.10.0          nompi_py36hecadee3_104    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_100    conda-forge
hmmer                     3.3                  he1b5a44_1    bioconda
icu                       67.1                 he1b5a44_0    conda-forge
inflection                0.3.1                      py_1    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
kiwisolver                1.2.0            py36hdb11119_0    conda-forge
krb5                      1.17.1               hfafb76e_1    conda-forge
krona                     2.7.1                   pl526_3    bioconda
lazy-object-proxy         1.5.1            py36h8c4c3a4_0    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.34                 hc38a660_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_3    conda-forge
libedit                   3.1.20191231         h46ee950_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0               hdf63c60_10    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libpq                     12.3                 h5513abc_0    conda-forge
libssh2                   1.9.0                hab1572f_4    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
matplotlib-base           3.3.0            py36h5ffbc53_1    conda-forge
mfqe                      0.5.0                h516909a_0    bioconda
mysql-connector-c         6.1.11            h876a3cc_1006    conda-forge
mysqlclient               1.4.6            py36h831f99a_1    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
numpy                     1.19.1           py36h7314795_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
orator                    0.9.9                      py_0    conda-forge
orfm                      0.7.1                hed695b0_2    bioconda
pandas                    1.0.5            py36h830a2c2_0    conda-forge
pastel                    0.1.0                      py_1    conda-forge
pendulum                  1.5.0                    py36_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pillow                    7.2.0            py36h8328e55_1    conda-forge
pip                       20.1.1                     py_1    conda-forge
pplacer                   1.1.alpha19                   1    bioconda
psycopg2                  2.8.5            py36h45558ae_1    conda-forge
pyaml                     16.12.2                  py36_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pylev                     1.3.0                      py_0    conda-forge
pymysql                   0.7.11                     py_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.6.11          h425cb1d_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pytzdata                  2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py36h8c4c3a4_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
scipy                     1.5.2            py36h3a855aa_0    conda-forge
setuptools                49.2.0           py36h9f0ad1d_0    conda-forge
simplejson                3.17.2           py36h8c4c3a4_0    conda-forge
singlem                   0.13.2                     py_0    bioconda
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smafa                     0.5.0                h516909a_0    bioconda
sqlalchemy                1.3.18           py36h8c4c3a4_0    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
squarify                  0.4.3                      py_0    conda-forge
taxtastic                 0.8.11                     py_0    bioconda
tempdir                   0.7.1                    py36_0    conda-forge
text-unidecode            1.2                        py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py36h8c4c3a4_1    conda-forge
tzlocal                   2.1                pyh9f0ad1d_0    conda-forge
vsearch                   2.15.0               h2d02072_0    bioconda
wheel                     0.34.2                     py_1    conda-forge
wrapt                     1.12.1           py36h8c4c3a4_1    conda-forge
xlrd                      1.2.0              pyh9f0ad1d_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```

**Comment by taylorreiter** [comment]
I'm able to generate this error with this smaller, example fastq file:

[ZeeviD_2015__PNP_Main_232__bin.27_small.fa.txt](https://github.com/wwood/singlem/files/4984865/ZeeviD_2015__PNP_Main_232__bin.27_small.fa.txt)

**Comment by wwood** [comment]
Hi Taylor,

Thanks for your interest and bug report.

I think this is likely due to singlem's (and graftm's) inability to autodetect file formats. You've provided a fastq file, but the ending is .fa.txt. When you specify it to singlem you use .fa according to your command. This confuses things because it is a fastq file, not a fasta one. Does the error go away when you rename the file?

ben

**Comment by taylorreiter** [comment]
Hi Ben, 

Thank you for your response! Renaming the file to end in `.fastq` does change the error message to:

```
file\\n[2020-07-27T22:52:35Z INFO  mfqe] Extracted 799 reads from 211938 total\\nthread \'main\' panicked at \'Mismatching numbers of read names were observed. Expected:\\n[711]\\nbut found\\n[799]\', src/main.rs:333:9\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n"STDOUT was: b\'\'\n'STDOUT was: b''
```

These are "subsetted" reads...I've used graph-based queries to extract reads from a graph neighborhood (detailed [here](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02066-4)), effectively grabbing ~50k reads of interest that should approximately correspond to one species in a metagenome. Is this messing up `mfqe`'s expectation for read names?

Full command/message below
```
$ singlem pipe --sequences ZeeviD_2015__PNP_Main_232__bin.27.fa.gz.cdbg_ids.reads.fastq --otu_table otu_table.csv --threads 2
07/27/2020 03:52:20 PM INFO: Using as input 1 different sequence files e.g. ZeeviD_2015__PNP_Main_232__bin.27.fa.gz.cdbg_ids.reads.fastq
07/27/2020 03:52:20 PM INFO: Searching with 14 SingleM package(s)
07/27/2020 03:52:20 PM INFO: Searching for reads matching 28 different protein HMM(s)
Traceback (most recent call last):
  File "/home/tereiter/miniconda3/envs/singlem/bin/singlem", line 513, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 45, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 176, in run_to_otu_table
    search_result = self._search(hmms, forward_read_files, reverse_read_files)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 860, in _search
    run(hmms, graftm_protein_search_directory, True)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 848, in run
    extern.run(cmd)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/extern/__init__.py", line 41, in run
    raise ExternCalledProcessError(process, command)
extern.ExternCalledProcessError: Command graftM graft --verbosity 2 --input_sequence_type nucleotide  --min_orf_length 96   --filter_minimum 28 --threads 2 --forward ZeeviD_2015__PNP_Main_232__bin.27.fa.gz.cdbg_ids.reads.fastq --search_only --search_hmm_files /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftm4ehmqY_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftmBf7aFs_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftm5WU6Uq_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftmSHqOh3_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmUShLiV_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmY0W8yc_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftme9CA2v_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftmmSefD1_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmhZA_92_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmrgaTTv_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.2.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmeZ00Qg_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.2.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmID8t_I_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spkg/S1.12.ribosomal_protein_S12_S23/graftmD68DOf_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spkg/S1.12.ribosomal_protein_S12_S23/graftm4bucq1_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftmCpbnSc_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftm5YNr6y_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmSIv4ri_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmh8KCUY_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.4.ribosomal_protein_L6_rplF.gpkg.spkg/S1.4.ribosomal_protein_L6_rplF/graftmDE7_8b_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.4.ribosomal_protein_L6_rplF.gpkg.spkg/S1.4.ribosomal_protein_L6_rplF/graftmr_l5Gy_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmAbXN7F_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmWRo94z_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmFIm7K0_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmMH5eE7_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.10.ribosomal_protein_S7.gpkg.spkg/S1.10.ribosomal_protein_S7/graftmunofJO_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.10.ribosomal_protein_S7.gpkg.spkg/S1.10.ribosomal_protein_S7/graftmvR14Hx_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftmAiWqW8_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftmIkMbHN_search.hmm --output_directory /dev/shm/tmp2816925b/graftm_protein_search --aln_hmm_file /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftm4ehmqY_search.hmm  returned non-zero exit status 1.
STDERR was: b'Traceback (most recent call last):\n  File "/home/tereiter/miniconda3/envs/singlem/bin/graftM", line 415, in <module>\n    Run(args).main()\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/run.py", line 613, in main\n    self.graft()\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/run.py", line 388, in graft\n    diamond_db\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/timeit.py", line 10, in timed\n    result = method(*args, **kw)\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 851, in aa_db_search\n    hit_reads_orfs_fasta)\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 943, in search_and_extract_orfs_matching_protein_database\n    hits\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 534, in _extract_from_raw_reads\n    extern.run(extract_cmd, stdin=\'\\n\'.join(input_reads))\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/extern/__init__.py", line 41, in run\n    raise ExternCalledProcessError(process, command)\nextern.ExternCalledProcessError: Command mfqe --output-uncompressed --fasta-read-name-lists /dev/stdin --input-fasta <(awk \'{print ">" substr($0,2);getline;print;getline;getline}\' \'ZeeviD_2015__PNP_Main_232__bin.27.fa.gz.cdbg_ids.reads.fastq\') --output-fasta-files \'/tmp/_raw_extracted_reads.famrkl3i_z\' returned non-zero exit status 101.\nSTDERR was: b"[2020-07-27T22:52:34Z INFO  mfqe] Read in 711 read names from /dev/stdin\\n[2020-07-27T22:52:34Z INFO  mfqe] Iterating input FASTQ file\\n[2020-07-27T22:52:35Z INFO  mfqe] Extracted 799 reads from 211938 total\\nthread \'main\' panicked at \'Mismatching numbers of read names were observed. Expected:\\n[711]\\nbut found\\n[799]\', src/main.rs:333:9\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n"STDOUT was: b\'\'\n'STDOUT was: b''
```

**Comment by wwood** [comment]
yeh maybe - you can't mix forward and reverse reads because the read names before the first space are identical. Separate them into different files and then use --forward and --reverse I think

**Comment by taylorreiter** [comment]
annoyingly, I can't split to F/R reads because pairs are not extracted by spacegraphtcats, but rather only reads that contain k-mers that were in the neighborhood of a query. 

However,

```
cat ZeeviD_2015__PNP_Main_232__bin.27.fa.gz.cdbg_ids.reads.fastq | awk '{print (NR%4 == 1) ? "@1_" ++i : $0}' | gzip -c > renamed.fastq.gz
```

Fixed the naming scheme and made graftm happy. Thank you for your help!

**Comment by wwood** [comment]
Makes sense. One subtle thing though - when you specify forward and reverse separately the result can be different to treating each read as forward, because if an OTU is found in both the forward and reverse of a pair, it is only counted once (since that is only a single observation rather than 2 independent ones). A small thing though, and may not make any difference.

Closing now, let me know if there's anything else.
ben
