### ISSUE TITLE
Error: Sequence file - is empty or misformatted caused by fastq file with 32-75bp sequences.

### ISSUE THREAD

**Issue by taylorreiter** [wwood/singlem#54]
Using the command:

```
$ singlem pipe --sequences tmp.fastq --otu_table tmp.csv --output_extras --threads 4
```
I receive the following error:
```
07/31/2020 09:49:14 AM INFO: Using as input 1 different sequence files e.g. tmp.fastq
07/31/2020 09:49:14 AM INFO: Searching with 14 SingleM package(s)
07/31/2020 09:49:14 AM INFO: Searching for reads matching 28 different protein HMM(s)
Traceback (most recent call last):
  File "/home/tereiter/miniconda3/envs/singlem/bin/singlem", line 513, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 45, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 176, in run_to_otu_table
    search_result = self._search(hmms, forward_read_files, reverse_read_files)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 860, in _search
    run(hmms, graftm_protein_search_directory, True)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 848, in run
    extern.run(cmd)
  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/extern/__init__.py", line 41, in run
    raise ExternCalledProcessError(process, command)
extern.ExternCalledProcessError: Command graftM graft --verbosity 2 --input_sequence_type nucleotide  --min_orf_length 96   --filter_minimum 28 --threads 4 --forward tmp.fastq --search_only --search_hmm_files /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftm4ehmqY_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftmBf7aFs_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftm5WU6Uq_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftmSHqOh3_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmUShLiV_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmY0W8yc_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftme9CA2v_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftmmSefD1_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmhZA_92_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmrgaTTv_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.2.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmeZ00Qg_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.2.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmID8t_I_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spkg/S1.12.ribosomal_protein_S12_S23/graftmD68DOf_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spkg/S1.12.ribosomal_protein_S12_S23/graftm4bucq1_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftmCpbnSc_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftm5YNr6y_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmSIv4ri_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmh8KCUY_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.4.ribosomal_protein_L6_rplF.gpkg.spkg/S1.4.ribosomal_protein_L6_rplF/graftmDE7_8b_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.4.ribosomal_protein_L6_rplF.gpkg.spkg/S1.4.ribosomal_protein_L6_rplF/graftmr_l5Gy_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmAbXN7F_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmWRo94z_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmFIm7K0_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmMH5eE7_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.10.ribosomal_protein_S7.gpkg.spkg/S1.10.ribosomal_protein_S7/graftmunofJO_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.10.ribosomal_protein_S7.gpkg.spkg/S1.10.ribosomal_protein_S7/graftmvR14Hx_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftmAiWqW8_search.hmm /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftmIkMbHN_search.hmm --output_directory /dev/shm/tmphn23kf8j/graftm_protein_search --aln_hmm_file /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftm4ehmqY_search.hmm  returned non-zero exit status 1.
STDERR was: b'Traceback (most recent call last):\n  File "/home/tereiter/miniconda3/envs/singlem/bin/graftM", line 415, in <module>\n    Run(args).main()\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/run.py", line 613, in main\n    self.graft()\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/run.py", line 388, in graft\n    diamond_db\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/timeit.py", line 10, in timed\n    result = method(*args, **kw)\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 851, in aa_db_search\n    hit_reads_orfs_fasta)\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 908, in search_and_extract_orfs_matching_protein_database\n    orfm\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 221, in hmmsearch\n    searcher.hmmsearch(input_cmd, self.search_hmm, output_table_list)\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/hmmsearcher.py", line 69, in hmmsearch\n    raise e\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/hmmsearcher.py", line 64, in hmmsearch\n    extern.run(cmd)\n  File "/home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/extern/__init__.py", line 41, in run\n    raise ExternCalledProcessError(process, command)\nextern.ExternCalledProcessError: Command orfm  -m 96 <(awk \'{print ">" substr($0,2);getline;print;getline;getline}\' \'tmp.fastq\') | tee >(hmmsearch --domE 1e-05 --cpu 1 -o /dev/null --noali --domtblout /dev/shm/tmphn23kf8j/graftm_protein_search/tmp/graftm4ehmqY_search_tmp.hmmout.txt /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftm4ehmqY_search.hmm -) | tee >(hmmsearch --domE 1e-05 --cpu 1 -o /dev/null --noali --domtblout /dev/shm/tmphn23kf8j/graftm_protein_search/tmp/graftmBf7aFs_search_tmp.hmmout.txt /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftmBf7aFs_search.hmm -) | tee >(hmmsearch --domE 1e-05 --cpu 1 -o /dev/null --noali --domtblout /dev/shm/tmphn23kf8j/graftm_protein_search/tmp/graftm5WU6Uq_search_tmp.hmmout.txt /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftm5WU6Uq_search.hmm -) | hmmsearch --domE 1e-05 --cpu 1 -o /dev/null --noali --domtblout /dev/shm/tmphn23kf8j/graftm_protein_search/tmp/graftmSHqOh3_search_tmp.hmmout.txt /home/tereiter/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftmSHqOh3_search.hmm - returned non-zero exit status 1.\nSTDERR was: b\'\\nError: Sequence file - is empty or misformatted\\n\\n\\nError: Sequence file - is empty or misformatted\\n\\n\\nError: Sequence file - is empty or misformatted\\n\\n\\nError: Sequence file - is empty or misformatted\\n\\n\'STDOUT was: b\'\'\n'STDOUT was: b''
```

Thinking this may be a case where fastq is misdetected as fasta, I converted the fastq files to fasta and re-ran and received the same error.

When I run fastqc, it completes, leading me to believe this is a valid fastq file. 
However, I notice that the sequence length distribution is`Sequence length 32-75` base pairs.

Using the command
```
singlem pipe --sequences tmp.fastq.gz --otu_table tmp.csv --output_extras --threads 4 --filter_minimum_nucleotide 36 --min_orf_length 36 --filter_minimum_protein 12
```

Allows singlem to complete. Is this a very bad idea re:accuracy of single marker genes to run singlem like this?
I've run singlem on about ~25,000 samples, and on ~5000 of them this was a problem. If I use the above parameters to allow the 5000 to complete, should I re-run singlem on the other 20,000 files in order to compare between all samples?

**Comment by wwood** [comment]
Thanks again for the chat today @taylorreiter - let me know if you've any further questions.
