### ISSUE TITLE
diamond_prefilter: Problem with --forward and --reverse?

### ISSUE THREAD

**Issue by wwood** [wwood/singlem#61]
@rzhao-2 is it possible that it doesn't work with --reverse? Maybe add a test case for this?
Thanks

```
$ ~/git/singlem-local/bin/singlem pipe --diamond_prefilter --forward sra_cache/SRR2189670_1.fastq.gz --reverse sra_cache/SRR2189670_2.fastq.gz --threads 8 --otu_table sra_cache/SRR2189670.otu_table.r95.csv
12/16/2020 12:00:23 PM INFO: Using as input 1 different sequence files e.g. sra_cache/SRR2189670_1.fastq.gz
12/16/2020 12:00:23 PM INFO: Filtering sequence files through DIAMOND blastx
Traceback (most recent call last):
  File "/home/ben/git/singlem-local/bin/singlem", line 531, in <module>
    diamond_prefilter = args.diamond_prefilter)
  File "/home/ben/git/singlem-local/bin/../singlem/pipe.py", line 45, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/home/ben/git/singlem-local/bin/../singlem/pipe.py", line 189, in run_to_otu_table
    reverse_read_files = self._prefilter(hmms, reverse_read_files)
  File "/home/ben/git/singlem-local/bin/../singlem/pipe.py", line 838, in _prefilter
    os.mkdir(prefilter_dir)
FileExistsError: [Errno 17] File exists: '/dev/shm/tmp_wx77yuq/prefilter'
```

**Comment by wwood** [comment]
Now fixed in dev.
