### ISSUE TITLE
no_assign_taxonomy does not work with paired input

### ISSUE THREAD

**Issue by rzhao-2** [wwood/singlem#63]
Command used:
bin/singlem pipe --diamond_prefilter --no_assign_taxonomy --threads 8 --output_extras --forward /srv/projects/abisko/data/flat20150213/20120600_E2D.1.fq.gz --reverse /srv/projects/abisko/data/flat20150213/20120600_E2D.2.fq.gz --otu_table /srv/home/s4395835/test_rvs.csv

Output:
Traceback (most recent call last):
  File "bin/singlem", line 537, in <module>
    diamond_prefilter = args.diamond_prefilter)
  File "/srv/home/s4395835/singlem/bin/../singlem/pipe.py", line 45, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/srv/home/s4395835/singlem/bin/../singlem/pipe.py", line 248, in run_to_otu_table
    package_to_taxonomy_bihash)
  File "/srv/home/s4395835/singlem/bin/../singlem/pipe.py", line 631, in _process_taxonomically_assigned_reads
    new_infos = process_readset(maybe_paired_readset, analysing_pairs)
  File "/srv/home/s4395835/singlem/bin/../singlem/pipe.py", line 585, in process_readset
    aligned_seqs = readset.unknown_sequences
AttributeError: 'list' object has no attribute 'unknown_sequences'

**Comment by wwood** [comment]
This is now fixed in the dev branch.
