### ISSUE TITLE
krona issue

### ISSUE THREAD

**Issue by slambrechts** [wwood/singlem#75]
Dear Ben,

When trying to run: 

_singlem pipe --forward 101_R1.fastq.gz --reverse 101_R2.fastq.gz --otu_table 101_shtgn_singleM_otutab.csv --threads 36_

I get the following error message during the HMM search:

```
ERROR: The following programs appear to be missing, and need to be updated or installed before GraftM can continue:
03/12/2021 08:13:33 PM ERROR: 	       ktImportText/krona	http://sourceforge.net/p/krona/home/krona/
```

However, KronaTools seems to be installed and loaded (version 2.7.1), and `graftM --help` behaves normal

Any idea what is causing this?

Full error message:

```
03/12/2021 08:13:31 PM INFO: Using as input 1 different sequence files e.g. 101_R1.fastq.gz
03/12/2021 08:13:31 PM INFO: Searching with 14 SingleM package(s)
03/12/2021 08:13:31 PM INFO: Searching for reads matching 28 different protein HMM(s)
Traceback (most recent call last):
  File "/apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/bin/singlem", line 509, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/pipe.py", line 46, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/pipe.py", line 168, in run_to_otu_table
    search_result = self._search(hmms, forward_read_files, reverse_read_files)
  File "/apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/pipe.py", line 846, in _search
    run(hmms, graftm_protein_search_directory, True)
  File "/apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/pipe.py", line 834, in run
    extern.run(cmd)
  File "/apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/extern/__init__.py", line 46, in run
    stdout)
extern.ExternCalledProcessError: Command graftM graft --verbosity 2 --input_sequence_type nucleotide  --min_orf_length 96   --filter_minimum 28 --threads 36 --forward 101_R1.fastq.gz --search_only --search_hmm_files /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmAbXN7F_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmWRo94z_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftme9CA2v_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftmmSefD1_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmFIm7K0_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmMH5eE7_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.10.ribosomal_protein_S7.gpkg.spkg/S1.10.ribosomal_protein_S7/graftmunofJO_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.10.ribosomal_protein_S7.gpkg.spkg/S1.10.ribosomal_protein_S7/graftmvR14Hx_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftmAiWqW8_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftmIkMbHN_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftm4ehmqY_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftmBf7aFs_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftm5WU6Uq_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftmSHqOh3_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmhZA_92_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmrgaTTv_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.4.ribosomal_protein_L6_rplF.gpkg.spkg/S1.4.ribosomal_protein_L6_rplF/graftmDE7_8b_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.4.ribosomal_protein_L6_rplF.gpkg.spkg/S1.4.ribosomal_protein_L6_rplF/graftmr_l5Gy_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spkg/S1.12.ribosomal_protein_S12_S23/graftmD68DOf_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spkg/S1.12.ribosomal_protein_S12_S23/graftm4bucq1_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmUShLiV_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmY0W8yc_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.2.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmeZ00Qg_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.2.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmID8t_I_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftmCpbnSc_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftm5YNr6y_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmSIv4ri_search.hmm /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmh8KCUY_search.hmm --output_directory /dev/shm/tmp6j3SYW/graftm_protein_search --aln_hmm_file /apps/gent/CO7/skylake-ib/software/SingleM/0.12.1-intel-2019a-Python-2.7.15/lib/python2.7/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmAbXN7F_search.hmm --reverse 101_R2.fastq.gz  returned non-zero exit status 1.
STDERR was: 03/12/2021 08:13:33 PM ERROR: The following programs appear to be missing, and need to be updated or installed before GraftM can continue:
03/12/2021 08:13:33 PM ERROR: 	       ktImportText/krona	http://sourceforge.net/p/krona/home/krona/

`
```
Kind regards,
Sam

**Comment by wwood** [comment]
Hi,

At first glance seems like krona is not installed properly. Does 'ktImportText' work from the command line?

**Comment by slambrechts** [comment]
Hi,

No indeed, it doesn't, that results in: `-bash: ktImportText: command not found`

On https://github.com/marbl/Krona/wiki/Installing I read the following: 

"To use these tools, updateTaxonomy.shmust be run after installing. This will install the local taxonomy database, which uses less than 100Mb of disk space and should take a few minutes or less to run. It can also be run later to keep the local database up to date with NCBI."

and

"To use these tools, updateAccessions.sh must be run after installing. This will install the local accession-to-taxonomyID database."

So I suspect it has something to do with that? But I'm trying to run singlem on an hpc system, so I can't modify the installation myself. I have sent the question to our sysadmin. I will post the cause and solution when they find it

thanks
