### ISSUE TITLE
Condense field limit:

### ISSUE THREAD

**Issue by EisenRa** [wwood/singlem#89]
Hi Ben,

Ran into an issue when trying to condense a particularly large pipe file:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Eisen.Raph/Desktop/Analyses/singlem-condense/singlem/bin/singlem", line 1006, in <module>
    Condenser().condense(
  File "/mnt/c/Users/Eisen.Raph/Desktop/Analyses/singlem-condense/singlem/bin/../singlem/condense.py", line 32, in condense
    for condensed_table in to_yield:
  File "/mnt/c/Users/Eisen.Raph/Desktop/Analyses/singlem-condense/singlem/bin/../singlem/condense.py", line 83, in condense_to_otu_table
    for sample, sample_otus in input_otu_table.each_sample_otus():
  File "/mnt/c/Users/Eisen.Raph/Desktop/Analyses/singlem-condense/singlem/bin/../singlem/otu_table_collection.py", line 239, in each_sample_otus
    for otu in self:
  File "/mnt/c/Users/Eisen.Raph/Desktop/Analyses/singlem-condense/singlem/bin/../singlem/otu_table_collection.py", line 221, in __iter__
    for otu in OtuTable.each(f):
  File "/mnt/c/Users/Eisen.Raph/Desktop/Analyses/singlem-condense/singlem/bin/../singlem/otu_table.py", line 19, in each
    for i, d in enumerate(csv.reader(otu_table_io, delimiter="\t")):
_csv.Error: field larger than field limit (131072)
```

I presume this is because the pipe file has a field that is too large? I've attached the troublesome pipe file.

[AI7_1b.tsv.gz](https://github.com/wwood/singlem/files/8988053/AI7_1b.tsv.gz)

Cheers,
Raphael

**Comment by wwood** [comment]
Thanks Raphael,

This is because the pipe file was created with --output-extras, which writes columns can be very large e.g. a whole chromosome's sequence if run on a complete genome. To workaround, you can just remove the extra columns with `cut` (everything up to and including the taxonomy column) or just run pipe again without --output-extras.

Still a bug tho - thanks for the report - doesn't seem hard to fix by changing the limit.

**Comment by wwood** [comment]
Glad it is solved for you, but reopening until it is fixed for real.
