### ISSUE TITLE
deadlock issue

### ISSUE THREAD

**Issue by wwood** [wwood/singlem#9]
Seem to be getting deadlock in `extern.run_many` somehow e.g.
```
uqbwoodc@mrca002:20160418:/srv/projects/paperpalooza/mock/8_mock_reference5$ f singlem pipe --sequences individuals/*a --otu_table mock_reference5.singlem.csv --threads 15                                         
04/18/2016 10:20:48 AM INFO: Using as input 58 different sequence files e.g. individuals/10.fna
04/18/2016 10:20:48 AM INFO: Running GraftM to find particular reads..
04/18/2016 10:34:12 AM INFO: Finished running GraftM search phase
04/18/2016 10:34:12 AM WARNING: Sample '98' does not appear to contain any hits
04/18/2016 10:34:12 AM INFO: Running separate alignments in GraftM..
^CTraceback (most recent call last):
  File "/srv/sw/singlem/0.5.0/bin/singlem", line 300, in <module>
    singlem_packages = args.singlem_packages)
  File "/srv/sw/singlem/0.5.0/bin/../singlem/pipe.py", line 216, in run
    extern.run_many(commands, num_threads=num_threads)
  File "/srv/sw/extern/0.1.0/lib/python2.7/site-packages/extern/__init__.py", line 70, in run_many
    return runner.run(commands, progress_stream=progress_stream)
  File "/srv/sw/extern/0.1.0/lib/python2.7/site-packages/extern/multi_runner.py", line 73, in run
    writeProc.join()
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/srv/sw/python/2.7.4/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/util.py", line 319, in _exit_function
    p.join()
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/srv/sw/python/2.7.4/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/util.py", line 319, in _exit_function
    p.join()
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```
Seems pretty reproducible, at least.

**Comment by wwood** [comment]
Fixed by fixing #1 I believe.
