### ISSUE TITLE
singlem error with conda installation

### ISSUE THREAD

**Issue by PuspenduSardar** [wwood/singlem#95]
Hi,

I have installed singlem with conda, and running the below command:
`singlem pipe --forward /home/ps897/sharing/pmb_study/fastq_files/SQ8353_1.fastq.gz --reverse /home/ps897/sharing/pmb_study/fastq_files/SQ8353_2.fastq.gz --otu_table SQ8353.csv --threads 92`

It threw up the following error:

08/04/2022 05:23:23 PM INFO: Using as input 1 different sequence files e.g. /home/ps897/sharing/pmb_study/fastq_files/SQ8353_1.fastq.gz
08/04/2022 05:23:23 PM INFO: Searching with 14 SingleM package(s)
08/04/2022 05:23:23 PM INFO: Searching for reads matching 28 different protein HMM(s)
Traceback (most recent call last):
  File "/home/ps897/miniconda3/envs/singlem/bin/singlem", line 513, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 45, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 176, in run_to_otu_table
    search_result = self._search(hmms, forward_read_files, reverse_read_files)
  File "/home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 860, in _search
    run(hmms, graftm_protein_search_directory, True)
  File "/home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/pipe.py", line 848, in run
    extern.run(cmd)
  File "/home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/extern/__init__.py", line 41, in run
    raise ExternCalledProcessError(process, command)
extern.ExternCalledProcessError: Command graftM graft --verbosity 2 --input_sequence_type nucleotide  --min_orf_length 96   --filter_minimum 28 --threads 92 --forward /home/ps897/sharing/pmb_study/fastq_files/SQ8353_1.fastq.gz --search_only --search_hmm_files /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmSIv4ri_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmh8KCUY_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftm5WU6Uq_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.14.ribosomal_protein_S19_rpsS.gpkg.spkg/S1.14.ribosomal_protein_S19_rpsS/graftmSHqOh3_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.2.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmeZ00Qg_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.2.ribosomal_protein_L3_rplC.gpkg.spkg/S1.2.ribosomal_protein_L3_rplC/graftmID8t_I_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmAbXN7F_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.7.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/S1.7.ribosomal_protein_L16_L10E_rplP/graftmWRo94z_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmFIm7K0_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.3.ribosomal_protein_L5_rplE.gpkg.spkg/S1.3.ribosomal_protein_L5_rplE/graftmMH5eE7_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.4.ribosomal_protein_L6_rplF.gpkg.spkg/S1.4.ribosomal_protein_L6_rplF/graftmDE7_8b_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.4.ribosomal_protein_L6_rplF.gpkg.spkg/S1.4.ribosomal_protein_L6_rplF/graftmr_l5Gy_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftme9CA2v_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.11.ribosomal_protein_S10_rpsJ.gpkg.spkg/S1.11.ribosomal_protein_S10_rpsJ/graftmmSefD1_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftm4ehmqY_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.9.ribosomal_protein_S5.gpkg.spkg/S1.9.ribosomal_protein_S5/graftmBf7aFs_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spkg/S1.12.ribosomal_protein_S12_S23/graftmD68DOf_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.12.ribosomal_protein_S12_S23.gpkg.spkg/S1.12.ribosomal_protein_S12_S23/graftm4bucq1_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmUShLiV_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.1.ribosomal_protein_L2_rplB.gpkg.spkg/S1.1.ribosomal_protein_L2_rplB/graftmY0W8yc_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftmAiWqW8_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.6.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/S1.6.ribosomal_protein_L14b_L23e_rplN/graftmIkMbHN_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmhZA_92_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.8.ribosomal_protein_S2_rpsB.gpkg.spkg/S1.8.ribosomal_protein_S2_rpsB/graftmrgaTTv_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.10.ribosomal_protein_S7.gpkg.spkg/S1.10.ribosomal_protein_S7/graftmunofJO_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.10.ribosomal_protein_S7.gpkg.spkg/S1.10.ribosomal_protein_S7/graftmvR14Hx_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftmCpbnSc_search.hmm /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.5.ribosomal_protein_L11_rplK.gpkg.spkg/S1.5.ribosomal_protein_L11_rplK/graftm5YNr6y_search.hmm --output_directory /dev/shm/tmpdj5zgfdi/graftm_protein_search --aln_hmm_file /home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/data/S1.13.ribosomal_protein_S15P_S13e.gpkg.spkg/S1.13.ribosomal_protein_S15P_S13e/graftmSIv4ri_search.hmm --reverse /home/ps897/sharing/pmb_study/fastq_files/SQ8353_2.fastq.gz  returned non-zero exit status 1.
STDERR was: b'Traceback (most recent call last):\n  File "/home/ps897/miniconda3/envs/singlem/bin/graftM", line 42, in <module>\n    from graftm.run import Run\n  File "/home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/run.py", line 28, in <module>\n    from graftm.archive import Archive\n  File "/home/ps897/miniconda3/envs/singlem/lib/python3.6/site-packages/graftm/archive.py", line 6, in <module>\n    from bird_tool_utils import in_tempdir\nModuleNotFoundError: No module named \'bird_tool_utils\'\n'STDOUT was: b''

I am not sure what went wrong. Could you please help me fix it?

Regards,
Puspendu

**Comment by wwood** [comment]
Hi,

Apologies for this. You can fix by running

```
conda install -c bioconda  bird_tool_utils_python
```

**Comment by wwood** [comment]
Actually I guess you are using pip not conda. So can just

```
pip install bird_tool_utils
```
instead

**Comment by PuspenduSardar** [comment]
> Hi,
> 
> Apologies for this. You can fix by running
> 
> ```
> conda install -c bioconda  bird_tool_utils_python
> ```

Hi,

Thanks a lot.
Conda install worked!

Completely different issue, is there a way to run singlem for any particular marker gene only (e.g. only rplB)? Please let me know if I should open a new issue for this question.

Regards,
Puspendu

**Comment by wwood** [comment]
Thanks. I've updated the bioconda recipe now so shouldn't happen to others any more - thanks for contributing.

>Completely different issue, is there a way to run singlem for any particular marker gene only (e.g. only rplB)? Please let me know if I should open a new issue for this question.

Yes, you can simply specify `--singlem_packages` to pipe and specify one or more singlem packages (.spkg folders) after. rplB comes with the pip install.

However, since rplB is included in the default set, you can get the same result by running with default parameters and then ignoring the results for the other marker genes. Is there some particular reason why you want to only run one gene? Speed? Ease of analysis in that you only need to look at the results for a single marker instead of all of them?

Thanks, ben

**Comment by PuspenduSardar** [comment]
> Thanks. I've updated the bioconda recipe now so shouldn't happen to others any more - thanks for contributing.
> 
> > Completely different issue, is there a way to run singlem for any particular marker gene only (e.g. only rplB)? Please let me know if I should open a new issue for this question.
> 
> Yes, you can simply specify `--singlem_packages` to pipe and specify one or more singlem packages (.spkg folders) after. rplB comes with the pip install.
> 
> However, since rplB is included in the default set, you can get the same result by running with default parameters and then ignoring the results for the other marker genes. Is there some particular reason why you want to only run one gene? Speed? Ease of analysis in that you only need to look at the results for a single marker instead of all of them?
> 
> Thanks, ben

Hi,

Thanks a lot.
The reason for running one gene is more like the second one. It's easy to check the result (and less time to run).
With conda, can I download the .spkg from the singlem github repository and pipe it with `--singlem_packages`?

Regards,
Puspendu
