### ISSUE TITLE
Cannot create singlem package using tree-less graftm package

### ISSUE THREAD

**Issue by rzhao-2** [wwood/singlem#97]
Hi, just found that the package creator isn't able to handle an input graftm package that has no tree file.

```
bin/singlem create --force --target-domains Viruses --gene-description "" --input-graftm-package /mnt/hpccs01/work/microbiome/msingle/rossenzhao/vogdb211/gpkgs/VOG00805.gpkg --hmm-position 454 --input-taxonomy /mnt/hpccs01/work/microbiome/msingle/rossenzhao/vogdb211/viral_taxonomy_fixed.tsv --output-singlem-package /mnt/hpccs01/work/microbiome/msingle/rossenzhao/vogdb211/spkgs_no_bait/VOG00805.spkg
09/05/2022 12:28:51 PM INFO: SingleM v0.13.2
09/05/2022 12:28:52 PM INFO: Detected package type as protein
Traceback (most recent call last):
  File "/home/n10927662/singlem/bin/singlem", line 951, in <module>
    PackageCreator().create(input_graftm_package = args.input_graftm_package,
  File "/mnt/home/n10927662/singlem/bin/../singlem/package_creator.py", line 38, in create
    path=gpkg.reference_package_tree_path(),
  File "/home/n10927662/e/singlem/lib/python3.10/site-packages/graftm/graftm_package.py", line 160, in reference_package_tree_path
    self._refpkg_contents()['files']['tree'])
KeyError: 'tree'
```

**Comment by wwood** [comment]
Hmm, odd. I think Sam has done this somehow already though - maybe check with him?

**Comment by rzhao-2** [comment]
I don't think he has, the code where package_creator handles trees doesn't really have a case for where the tree doesn't exist.

**Comment by wwood** [comment]
OK, still, have a chat with him if you haven't already - he might provide guidance.
